### ISSUE TITLE
Autonode not recognizing node sync state. looping re-activation of validator

### ISSUE THREAD

**Issue by danbedford** [harmony-one/auto-node#16]
Shard 0 node went down at epoch 1057. Checked status:

```
./auto_node.sh status
  File "/home/harmony/.local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/harmony/.local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/harmony/.local/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.s0.os.hmny.io', port=443): Read timed out. (read timeout=3)
Auto node failed with error: HTTPSConnectionPool(host='api.s0.os.hmny.io', port=443): Read timed out. (read timeout=3)

Waiting for network response before raising exception for daemon restart.
```

Notified @fxfactorial who confirmed the endpoints were running well, however the node was still "waiting for network response".

Manually restarted autonode with `./auto_node.sh kill` and then `./auto_node.sh run --auto-active --auto-reset` and it's working, however, it's showing the current epoch is synced to 306. Autonode is not recognizing that the node is not synced and it's sending an "activate" tx for the validator. I noticed this in the output and closed out in order to manually send a "deactivate" tx so the node can catch up first. Autonode recognized this and re-activated it.

Node gets elected next epoch because stake is high enough, all blocks are missed, val kicked next epoch, autonode reactivates val, all blocks are missed, val kicked next epoch, and so on.

**Comment by Daniel-VDM** [comment]
This got fixed in the latest version, a check is made for the state before sending the transaction.
