### ISSUE TITLE
autonode cannot replace existing auto_node.sh file

### ISSUE THREAD

**Issue by yelllowsin** [harmony-one/auto-node#18]
I ran the latest version available [here](https://gist.github.com/Daniel-VDM/7a0f3f53ce7b3cee5a2008267d6169a7) and i the installation script had an issue replacing the existing `auto_node.sh` file. 

I made sure to kill the previous version before upgrading, and though it asks for me if i want to replace the file, it actually does not do it when i answer yes. See prinscreen bellow:

`./auto_node.sh kill`

![replace_file](https://user-images.githubusercontent.com/7217595/79769679-cd8d8a80-8302-11ea-9247-822d10905b14.jpg)

**Comment by Daniel-VDM** [comment]
Thx for reporting should be fixed in the latest version.
