### ISSUE TITLE
[AutoNode] Waiting for http://localhost:9500 to respond

### ISSUE THREAD

**Issue by yelllowsin** [harmony-one/auto-node#22]
We are having issues with some users running the latest version of AutoNode from Master:

`curl -O https://raw.githubusercontent.com/harmony-one/auto-node/master/scripts/install.sh && chmod +x ./install.sh && ./install.sh && rm ./install.sh`

They have reported me that the issue happens even on a fresh installed vps instance. I have seen this issue happening to me in the earlier version but luckly i didn't have it again. Unfortunately at least other 3 users reported it today on the Volunteers channel. I checked with them and they were running the lastest. I think this problem is still going on. I am attaching some prinscreeens and logs:

![710253ee-e7b4-4946-a8ee-7dd8cf0ba49f](https://user-images.githubusercontent.com/7217595/80116562-81d61d80-855c-11ea-9c7b-11774b3d9be4.jpg)
![c0f9ddba-6aeb-4ece-a6bc-bb26899cb0c3](https://user-images.githubusercontent.com/7217595/80116574-84387780-855c-11ea-8067-664dd192ae02.jpg)

I asked one of them to do a telnet test on localhost just to see if it was responding on port 9500 and it was not listening/down:

`telnet localhost 9500`

One of them had this trace error when exiting the screen:

```
Traceback (most recent call last):
  File "/home/administrator/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/administrator/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/administrator/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9500): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1aca714e10>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by joesixpack** [comment]
I too have this issue and its been occuring for at least two previous AutoNode versions.  Back to the old way for now.  I have yet to successfully run AutoNode due to various bugs.

**Comment by yelllowsin** [comment]
Another user (Sage_Knight) reported this problem today, so it it still ongoing:

> "The messages is same, repeated as you know it, now it's reach 340sec;
 Waiting for http://localhost:9500/ to respond, tried 340 times (~340 seconds waited so far)"
