### ISSUE TITLE
autonode has problems with pyhton in ubuntu 16

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/auto-node#23]
So looks like somehow it doesnt recognize that the right version is installed:

![photo_2020-04-24_00-58-31](https://user-images.githubusercontent.com/55639830/80158145-14f86d00-85c8-11ea-9953-8792af1452a1.jpg)

"Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-56uom3jc/AutoNode/
You are using pip version 8.1.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command." but i'm already uptodate

![photo_2020-04-24_00-58-23](https://user-images.githubusercontent.com/55639830/80158191-32c5d200-85c8-11ea-8202-b346960226c1.jpg)

user switched to ubuntu 18 and it works now

**Comment by rhazberries** [comment]
In the first screenshot, it says `python2.7`. AutoNode requires Python3.6.

Come with Ubuntu 18.04 by default. Otherwise, they will need to install it.
Will add a check for Python version.

**Comment by Daniel-VDM** [comment]
Added an auto-update from python3.5 --> python3.6 if using an older version of ubuntu. Latest PR will also upgrade pip3 as part of the install
