### ISSUE TITLE
Feature Request - Stop using docker.io and use Docker CE

### ISSUE THREAD

**Issue by JB273** [harmony-one/auto-node#3]
Hey Daniel,

I just realized you're using docker.io, although this build seems to be working in most cases it is actually an old build of docker...
People are running into weird problems with setting up autonode!

I would like to propose that we are going to use docker CE to make sure we are on the newest build. Please see here https://docs.docker.com/engine/install/ubuntu/ and here https://docs.docker.com/engine/install/binaries/

**Comment by yelllowsin** [comment]
@JB273 I think you can close this one. We migrated off docker already: https://docs.harmony.one/home/validators/autonode
